version: "2"
services:
  web:
    image: nginx:1.13-alpine
    networks:
     - network
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ~/.certs:/etc/certs
    ports:
     - "443:443"
  ghost:
    image: ghost:1-alpine
    restart: always
    env_file:
     - ~/.secrets/ghost.env
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__database: ghost
    networks:
     - network
  db:
    image: mysql:5.7
    volumes:
     - ./datadir:/var/lib/mysql
    env_file:
     - ~/.secrets/ghost.env
    restart: always
    networks:
     - network
networks:
  network:
